//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Physio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.PatientAnswers = new HashSet<PatientAnswer>();
            this.QuestionSetQuestions = new HashSet<QuestionSetQuestion>();
        }
    
        public int Id { get; set; }
        public string QuestionTitle { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public string QuestionAbbreviation { get; set; }
        public string QuestionHint { get; set; }
        public string UIcaption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAnswer> PatientAnswers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionSetQuestion> QuestionSetQuestions { get; set; }
    }
}
